### ISSUE TITLE
RelayHttpServer reinstall not working

### ISSUE THREAD

**Issue by ClarenceL** [OpenZeppelin/openzeppelin-gsn-helpers#30]
I deleted the `/app/data` folder by accident, now it keeps failing, how do I properly remove everything?

0/03/30 12:25:23 RelayHttpServer.go:218: Using workdir: /app/data
2020/03/30 12:25:23 RelayHttpServer.go:228: Constructing relay server in url  https://gsn-relayer.elastosjs.com
2020/03/30 12:25:23 utils.go:40: ks accounts len 1
2020/03/30 12:25:23 utils.go:66: key extracted. addr: 0x9E52cBF4F5F4547fa8A351De88572D6dc97eb7dE
2020/03/30 12:25:23 RelayHttpServer.go:230: relay server address:  0x9E52cBF4F5F4547fa8A351De88572D6dc97eb7dE
2020/03/30 12:25:23 RelayHttpServer.go:238: Could not create local transactions database resource temporarily unavailable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x86ab04]

goroutine 1 [running]:
main.main()
	/ext-go/1/src/relay/RelayHttpServer.go:48 +0x104

**Comment by ClarenceL** [comment]
It seems like `workingDir` isn't set and RelayHttpServer is just creating the /data/ folder in the same directory, which seems to at least get it running. I think my issue is I don't know how to properly reset the service and get it to run again with a new set of env variables.

**Comment by ClarenceL** [comment]
I think my misunderstanding was that each time the relayer was setup it had an arbitrary relay server address.
