### ISSUE TITLE
Error: "gas" is missing

### ISSUE THREAD

**Issue by Cr0wn-Gh0ul** [OpenZeppelin/openzeppelin-gsn-helpers#31]
This gets thrown when trying to use: deployRelayHub, runRelayer, registerRelay, runAndRegister.

```
    try {
      await deployRelayHub(this.web3, {
        from: this.web3.eth.defaultAccount,
      });
    } catch(ex) {
      console.log(ex)
    }

**Comment by nventuro** [comment]
Can you share some more information about your setup to help us reproduce this issue? The `gas` field is often estimated by the provider based on the transaction data, as opposed to being hard-coded at the callsite.

**Comment by Cr0wn-Gh0ul** [comment]
The provider in this case is Matic testnet, `https://testnet2.matic.network`. Although I did just try with Rinkeby infura and had the same issue. Here is a sample of the code: https://gist.github.com/Cr0wn-Gh0ul/a19d7c3a3a0e3874f0a3e01fc3274f50

**Comment by nventuro** [comment]
Sorry for the delay @Cr0wn-Gh0ul!

Unfortunately I've just successfully run your gist on the Rinkeby network using Infura with 0 issues. Which version of web3 are you using?

**Comment by Cr0wn-Gh0ul** [comment]
No problem. Its web3 version 1.2.6

**Comment by nventuro** [comment]
Thanks for being patient @Cr0wn-Gh0ul! I've now managed to reproduce your issue - I wonder if something changed on Infura behind the scenes? I'm looking into this in more detail and will report back with findings.

**Comment by rrodriguezreche** [comment]
I am having the same issue, dropping some debug lines:

```
Error: "gas" is missing
    at signed (/home/mad/geodb/rewards-emitter/relayHub/node_modules/web3-eth-accounts/src/index.js:158:21)
    at /home/mad/geodb/rewards-emitter/relayHub/node_modules/web3-eth-accounts/src/index.js:271:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This gets triggered when using `const { registerRelay } = require('@openzeppelin/gsn-helpers');`
